; -----------------------------------------------------------------
; Archery Focus - Slow Motion & Headshots - v1.30
; -----------------------------------------------------------------

; [Default: 1] Enable slow motion while zooming with bow.
set zzzArcherySH.Ini_EnableSlowMotion to 1
; [Default: 75%] Slow motion multiplier when Marksman skill is 50.
set zzzArcherySH.Ini_SlowMotionMult_Weak to 0.75
; [Default: 50%] Slow motion multiplier when Marksman skill is 75.
set zzzArcherySH.Ini_SlowMotionMult_Strong to 0.50
; [Default: 50] Marksman skill level required to trigger weak slow motion.
set zzzArcherySH.Ini_SlowMotionSkillThreshold_Weak to 50
; [Default: 75] Marksman skill level required to trigger strong slow motion.
set zzzArcherySH.Ini_SlowMotionSkillThreshold_Strong to 75

; [Default: 2] Enable headshot damage for bow attacks.
; 0 = Disabled, 1 = Characters only, 2 = Characters and creatures
set zzzArcherySH.Ini_EnableHeadshot to 2
; [Default: +100%] Additional damage multiplier for headshots.
set zzzArcherySH.Ini_HeadshotDamageMult to 0.50
; [Default: +200%] Additional damage multiplier for headshots while sneaking.
set zzzArcherySH.Ini_HeadshotDamageMultSneak to 0.50
; [Default: 180] Headshots will not trigger if enemy distance is less than this value.
set zzzArcherySH.Ini_HeadshotMinDistance to 150
; [Default: 1] Play sound when headshots are successful. 1=Enabled
set zzzArcherySH.Ini_HeadshotSound to 1
; [Default: 1] Show message when headshots are successful. 1=Enabled, 2=Enabled (Detailed)
set zzzArcherySH.Ini_HeadshotNotification to 1

; [Default: 0] Auto-equip arrows when current arrows run out.
; 0=Disabled, 1=Lowest damage arrow, 2=Highest damage arrow, 
; 3=Lowest damage arrow (including enchanted), 4=Highest damage arrow (including enchanted)
set zzzArcherySH.Ini_AutoEquipArrow to 0

; [Default: -1] Override knockdown chance for enemies with Marksman skill 75+. -1 disables override.
; This chance applies to all actors, not just the player.
set zzzArcherySH.Ini_KnockdownChance to -1

; [Default: -1] Override paralyze chance for enemies with Marksman skill 100+. -1 disables override.
; This chance applies to all actors, not just the player.
set zzzArcherySH.Ini_ParalyzeChance to -1

; [Default: 0] If set to 0.0 or higher, sets game speed to this value when loading savegame.
; If game speed becomes abnormally slow due to unexpected crashes, set to 1.0 to fix.
set zzzArcherySH.Ini_GameSpeedFix to 0.0

; [Default: 0.0050] Headshot monitoring interval for arrows fired by the player
set zzzArcherySH.Ini_ArrowMonitor to 0.010


;=================================
; !!!!!!! DO NOT CHANGE !!!!!!!
;=================================
set zzzArcherySH.Ini_VERSION to 130
