;=====================;
;  QZ Easy Menus.ini  ;
;   by qzilla v1.03   ;
;=====================;

; The numbers for keys are directX scancodes, which you can lookup here:
; http://cs.elderscrolls.com/constwiki/index.php/Template:DirectX_Scancodes
; Setting a key code to 0 will disable it.
; Default values are listed after the semi-colon

;========================;
;  Menu Escape Settings  ;
;========================;

; - iExitKey -
; This is the main exit key that lets you exit almost any menu
; - iAltExitKey -
; This is the alternate exit key, works just like the main one
; so basically you got two exit keys.
; - iModKey -
; When this key is set you will need to press it together with
; the ExitKey or the AltExitKey for them to work. Also, it must
; be pressed before them or it won't work.
; - iTakeKey -
; Special key that can be used for a few actions in menus like
; the 'Take All' in container menus, or the 'Take' button in
; books and scrolls, or the 'Repair All' button in the repair
; menu. This key ignores the above iModKey setting so you'll
; always only need to press this one.
set EasyMenu.iExitKey                to  257    ; 257 (Right Mouse Button)
set EasyMenu.iAltExitKey             to  0     ; 57  (Space)
set EasyMenu.iModKey                 to  0      ; 0   (None)
set EasyMenu.iTakeKey                to  184     ; 30  (A)

; - bOnlyConfirm -
; When this option is on you will only be able to use the
; ExitKey to exit a messagebox if it was generated by 
; the game itself, not by a script. Only when there is but
; one button can you use the ExitKey to close the script
; generated messagebox.
; - bUseNumKeys -
; This enables the use of the number keys (both Numpad and 
; non-Numpad ones) to select specific messagebox buttons
; or topics according to their order. For topics it needs to
; be visible (not hidden until you scroll down/up) to prevent
; accidentally selecting a topic that you couldn't even see.
; - bNumberizeTopics -
; This option only applies when bUseNumKeys is on and
; it gives each topic a numberic prefix to easily see
; which key you'd need to press to select that topic.
set EasyMenu.bOnlyConfirm            to  0      ; 1
set EasyMenu.bUseNumKeys             to  1      ; 1
set EasyMenu.bNumberizeTopics        to  1      ; 0

;===========================;
;  Journal Mode Quick Keys  ;
;===========================;

; - iModKey2 -
; Same functionality as the iModKey only this one
; affects the Quick-Keys listed below. Useful for when
; you'd like no modkey for the iExitKey but do want a
; modkey for the Quick-Keys (or the other way around).
; Can be the same as iModKey.
; - iMapWorldKey -
; Quick-key to go to the World Map
; - iMapLocalKey -
; Quick-key to go to the Local Map
; - iSkillsKey -
; Quick-key to go to the Skills page
; - iStatsKey -
; Quick-key to go to the Attributes page
; - iInvKey -
; Quick-key to go to the All Items page
; - iMagicKey -
; Quick-key to go to the All Spells page
; - iEffectsKey -
; Quick-key to go to the Active Effects page
; - iQuestAllKey -
; Quick-key to go to the Current Quests page
; - iQuestActiveKey -
; Quick-key to go to the Active Quest page
set EasyMenu.iModKey2                to  0      ; 29 (Left Control)
set EasyMenu.iMapWorldKey            to  50     ; 50 (M)
set EasyMenu.iMapLocalKey            to  51     ; 51 (<)
set EasyMenu.iSkillsKey              to  37     ; 37 (K)
set EasyMenu.iStatsKey               to  25    ; 25 (P)
set EasyMenu.iInvKey                 to  23     ; 23 (I)
set EasyMenu.iMagicKey               to  48     ; 48 (B)
set EasyMenu.iEffectsKey             to  49     ; 49 (N)
set EasyMenu.iQuestAllKey            to  36     ; 36 (J)
set EasyMenu.iQuestActiveKey         to  38     ; 38 (L)


