; ============================================================================
; This is the INI file for Supreme Magicka,
; Edit this file to customize to your preferences
; Place this in your Oblivion "Data" folder
;=============================================================================
set SMQuest.version to 7

set SMQuest.bEnableNewMagicEffects to 1	; If enabled levitation, reanimation, new summons and poison effects are enabled, and are available in shops and random loot drops

set SMQuest.bEnableNewSpells to 1 ; If enabled adds a collection of pre-made spells to shops. Also includes the circle effect spells.

set SMQuest.sMagicDurationBoost to 0 	; Multiplier for illusion, conjuration and alteration durations once player hits journeyman skill. Setting to 1 disables the effect.

set SMQuest.bSpellLeveling to 1 ; Enables the quest reward spells to level up on use if you have the magicka to cast the stronger spells. Setting to 0 disables this feature.

set SMQuest.bNightEyeItemDetection to 0 ; Enables night eye to detect surrounding items, chests and traps. Setting to 0 disables this feature.

set SMQuest.bNightEyeAuto to 0 ; Enables night eye to automatically disable in daylight and when holding a torch. Setting to 0 disables this feature.

set SMQuest.makeCircleKey to 45  ; Press and hold this key during spell making to toggle touch spell effects to be cast without a target. Defaults to X.

set SMQuest.bSummonEffect to 0  ; Set to 0 to disable the summon effect graphic.

set SMQuest.sSummonLimit to 2 ; At master skill number of different summons you can raise at the same time.

set SMQuest.bAttributeBonus to 0  ; Willpower, Intelligence and Personality provide bonuses to spell casting. Set to 0 to disable.

set SMQuest.bTeleBlink to 1  ; Enables the additional telekinesis blink effect. Set to 0 to disable.

set SMQuest.sFeatherDivisor to 4  ; Divides feather spell magnitude by this to determine how much extra jump height you gain. Set to 0 to disable additional jump bonus

; Stealth mechanics
set SMQuest.sNoisySpells to 20  ; When you cast a spell this much extra noise is generated making it harder to stay in stealth. 
				; Set to 0 to not generate any extra noise. Setting to 100 makes it near impossible to stay hidden after casting a spell.
set SMQuest.fMagicStealthMultiplier to 0  ; Multiplier of extra damage from a successful magic sneak attack at apprentice skill. Set to 0 for no extra damage.
set SMQuest.fMagicStealthNovMultiplier to 0  ; Multiplier of extra damage from a successful magic sneak attack at novice skill. Set to 0 for no extra damage.

; Magic Skill Progression
set SMQuest.bMagickaProgress to 0   ; Enables magic skill progression such that lower level and low cost spells do not provide as much XP 
set SMQuest.sMagicProgressCombatMod to 1.0 ; Multiplier to magic skill XP to reduce XP gain when not in combat. Set 1 to disable.

; == Optional Settings == 
set SMQuest.bTurnUndeadIsRestorationOption to 0 ; If enabled turn undead effects are moved to the restoration school

set SMQuest.bAbsorbIsMysticism to 0 ; If enabled absorb effects are moved to the mysticism school

set SMQuest.bWildEnchanter to 0 ; If enabled most magic effects that are normally locked from spell making and enchantment are now available.

set SMQuest.bEnableWildSpells to 0  ; If enabled a collection of spells that are unbalanced or lore breaking are available from shops.

set SMQuest.bMarkRecall to 1	; Enable mark/recall spells as mystic start spells and to shops. Recommended if you have disabled fast travel.

set SMQuest.bTouchFate to 0   ; Gives you a lesser power that strips essential status from any npc. Be careful how you use it.

set SMQuest.fMagicDamagePercent to 0 ; Increase or decrease the danger of magic attacks by this %
				       ; Positive value adds a weakness to magic effect to all characters, negative instead adds a resist magic effect

set SMQuest.sEnchantBoostPercent to 0 ; Boost amount of charge available on enchanted items by this percent

set SMQuest.bDisableDetectLife to 0 ; Disable the detect life colored shaders if using alternate detect life shaders. Note without such mods loaded after supreme magicka you may have no detect life effects at all.

set SMQuest.sRangeAOE to 2  ; To support playing in third person, all non custom made ranged effects will be given an AOE effect of this size. Recommended to set to 3 if used.

set SMQuest.sTouchAOE to 1  ; To support playing in third person, all non custom made touch effects will be given an AOE effect of this size and can casted without a target. Recommended to set to 2 if used.

; == Troubleshooting Settings ==  
set SMQuest.bDebug to 0	; Just enables Debug logging
set SMQuest.bDebugSpells to 0	; Adds a copy of every new spell or spells with new effects to the player for testing or cheating
set SMQuest.bDebugItems to 0  ; Adds some items that debug some magic effects for testing or cheating