;=============================================================================;
;                                                                             ;
; This is an advanced INI file for: Ultimate Leveling                         ;
; (IT MUST BE USED FOR THIS ADDON TO WORK CORRECTLY)                          ;
;                                                                             ;
; Edit this file to configure the appearance and position of UI elements.     ;
;                                                                             ;
; Place this in your "Data" folder                                            ;
;                                                                             ;
;=============================================================================;
; UI									      ;
;=============================================================================;
; By default the UI is automatically detected. If no UI is detected the
; vanilla UI will be used as default.
;
; -1 automatically detect UI
; 0 Vanilla UI
; 1 DarNified UI
; 2 DarkUId DarN UI
; 3 Northern UI
; 4 Dark Transparent UI
; 5 Major Jim's UI

set ULVL.ini_UI to -1

; By default a progress bar is added to show how close the player character
; is to leveling up. A progress text is added to show important events.
; No sound is played when the text is shown.
;
; You can change the appearance and position of the bar and text in the UI ini file.

set ULVL.ini_UI_progress_bar to 1
set ULVL.ini_UI_progress_text to 1
set ULVL.ini_UI_progress_sound to 0


;=============================================================================;
; Vanilla UI								      ;
;=============================================================================;
set ULVL.ini_config_UI 			to 0

set ULVL.ini_config_UI_bar_xp 		to sv_Construct "Menus\ULVL\HUD\hud_ribbon_xp.dds"
set ULVL.ini_config_UI_bar_rested	to sv_Construct "Menus\ULVL\HUD\hud_ribbon_rested.dds"
set ULVL.ini_config_UI_bar_zoom 	to 100
set ULVL.ini_config_UI_bar_x 		to 0
set ULVL.ini_config_UI_bar_y 		to 54
set ULVL.ini_config_UI_text_font 	to 3
set ULVL.ini_config_UI_text_shadow 	to 1
set ULVL.ini_config_UI_text_color_red	to 255
set ULVL.ini_config_UI_text_color_green	to 255
set ULVL.ini_config_UI_text_color_blue	to 255
set ULVL.ini_config_UI_text_x 		to 0
set ULVL.ini_config_UI_text_y 		to -54
SetStage ULVL 20


;=============================================================================;
; DarNified UI								      ;
;=============================================================================;
set ULVL.ini_config_UI 			to 1

set ULVL.ini_config_UI_bar_xp 		to sv_Construct "Menus\ULVL\HUD\hud_ribbon_xp.dds"
set ULVL.ini_config_UI_bar_rested	to sv_Construct "Menus\ULVL\HUD\hud_ribbon_rested.dds"
set ULVL.ini_config_UI_bar_zoom 	to 95
set ULVL.ini_config_UI_bar_x 		to 0
set ULVL.ini_config_UI_bar_y 		to 52
set ULVL.ini_config_UI_text_font 	to 2
set ULVL.ini_config_UI_text_shadow 	to 1
set ULVL.ini_config_UI_text_color_red	to 255
set ULVL.ini_config_UI_text_color_green	to 255
set ULVL.ini_config_UI_text_color_blue	to 255
set ULVL.ini_config_UI_text_x 		to 0
set ULVL.ini_config_UI_text_y 		to -30
SetStage ULVL 20


;=============================================================================;
; DarkUId DarN UI							      ;
;=============================================================================;
set ULVL.ini_config_UI 			to 2

set ULVL.ini_config_UI_bar_xp 		to sv_Construct "Menus\ULVL\HUD\hud_ribbon_xp.dds"
set ULVL.ini_config_UI_bar_rested	to sv_Construct "Menus\ULVL\HUD\hud_ribbon_rested.dds"
set ULVL.ini_config_UI_bar_zoom 	to 50
set ULVL.ini_config_UI_bar_x 		to 0
set ULVL.ini_config_UI_bar_y 		to 30
set ULVL.ini_config_UI_text_font 	to 2
set ULVL.ini_config_UI_text_shadow 	to 1
set ULVL.ini_config_UI_text_color_red	to 255
set ULVL.ini_config_UI_text_color_green	to 255
set ULVL.ini_config_UI_text_color_blue	to 255
set ULVL.ini_config_UI_text_x 		to 0
set ULVL.ini_config_UI_text_y 		to -30
SetStage ULVL 20


;=============================================================================;
; Northern UI								      ;
;=============================================================================;
set ULVL.ini_config_UI 			to 3

set ULVL.ini_config_UI_bar_xp 		to sv_Construct "Menus\ULVL\HUD\hud_ribbon_xp_northern.dds"
set ULVL.ini_config_UI_bar_rested	to sv_Construct "Menus\ULVL\HUD\hud_ribbon_rested_northern.dds"
set ULVL.ini_config_UI_bar_x 		to 135
set ULVL.ini_config_UI_bar_y 		to -16
set ULVL.ini_config_UI_text_font 	to 3
set ULVL.ini_config_UI_text_shadow 	to 1
set ULVL.ini_config_UI_text_color_red	to 255
set ULVL.ini_config_UI_text_color_green	to 255
set ULVL.ini_config_UI_text_color_blue	to 255
set ULVL.ini_config_UI_text_x 		to 0
set ULVL.ini_config_UI_text_y 		to -56
SetStage ULVL 20


;=============================================================================;
; Dark Transparent UI							      ;
;=============================================================================;
set ULVL.ini_config_UI 			to 4

set ULVL.ini_config_UI_bar_xp 		to sv_Construct "Menus\ULVL\HUD\hud_ribbon_xp.dds"
set ULVL.ini_config_UI_bar_rested	to sv_Construct "Menus\ULVL\HUD\hud_ribbon_rested.dds"
set ULVL.ini_config_UI_bar_zoom 	to 50
set ULVL.ini_config_UI_bar_x 		to -5
set ULVL.ini_config_UI_bar_y 		to 30
set ULVL.ini_config_UI_text_font 	to 2
set ULVL.ini_config_UI_text_shadow 	to 1
set ULVL.ini_config_UI_text_color_red	to 255
set ULVL.ini_config_UI_text_color_green	to 255
set ULVL.ini_config_UI_text_color_blue	to 255
set ULVL.ini_config_UI_text_x 		to 0
set ULVL.ini_config_UI_text_y 		to -30
SetStage ULVL 20


;=============================================================================;
; Major Jim's UI							      ;
;=============================================================================;
set ULVL.ini_config_UI 			to 5

set ULVL.ini_config_UI_bar_xp 		to sv_Construct "Menus\ULVL\HUD\hud_ribbon_xp.dds"
set ULVL.ini_config_UI_bar_rested	to sv_Construct "Menus\ULVL\HUD\hud_ribbon_rested.dds"
set ULVL.ini_config_UI_bar_zoom 	to 100
set ULVL.ini_config_UI_bar_x 		to 0
set ULVL.ini_config_UI_bar_y 		to 54
set ULVL.ini_config_UI_text_font 	to 3
set ULVL.ini_config_UI_text_shadow 	to 1
set ULVL.ini_config_UI_text_color_red	to 255
set ULVL.ini_config_UI_text_color_green	to 255
set ULVL.ini_config_UI_text_color_blue	to 255
set ULVL.ini_config_UI_text_x 		to 0
set ULVL.ini_config_UI_text_y 		to -54
SetStage ULVL 20
