 ;This INI file contains default setting for configuration variables.
;It is recommended to leave this file as-is and use ingame LINK menu to configure the mod settings.

;============ General ===============
set almQ.bMagickaSettings to 0
set almQ.bDisableSpellLevels to 1
set almQ.bEnableMagicSneakAttacks to 1
set almQ.bEnableSpellCombos to 1
set almQ.bEnableSkillBasedSpeeds to 1
set almQ.bIllegalMagic to 1
set almQ.bEnableProjectileControl to 0
set almQ.bAlternativeArmorPenalty to 0

;============ Alteration =============
set almQ.bLightAlteration to 1
set almQ.bUseLightColor to 1
set almQ.iLightR to 220
set almQ.iLightG to 240
set almQ.iLightB to 255
set almQ.bDispelLightOnSneak to 1
set almQ.iPreferredWeaponVFX to 0

;============= Conjuration ============
set almQ.bControlSummonLimit to 1
set almQ.iSummonLimitCap to 2
set almQ.bDefaultBoundWeapons to 1
set almQ.bDisableSoultrappingSummons to 0

;============= Destruction ============
set almQ.bEnvironmentalModifiers to 1
set almQ.bYellowLightning to 0
set almQ.bDrainHealthNoKill to 1

;============= Illusion ===============
set almQ.bPlayerParalysis to 0
set almQ.bCharmLimit to 1
set almQ.bChameleonNoRefraction to 0
set almQ.iKeyNEYE to 24
set almQ.bActiveInvisibility to 1

;============= Mysticism ==============
set almQ.bAbsorbMysticism to 1
set almQ.bDetectLifeOverhaul to 0
set almQ.bOverrideDeathDetection to 1
set almQ.fDispelDamageSummonMult to 0.0
set almQ.bAlternativeSpellAbsorbtion to 0

;============ Restoration =============
set almQ.bTurnRestoration to 1
set almQ.bTurnUndeadExpanded to 1
set almQ.bDisableREHEShader to 1

;============ Spellmaking =============
set almQ.bInstantSpells to 1
set almQ.iSpellmakingMaxMag to 100
set almQ.iSpellmakingMaxArea to 100
set almQ.iSpellmakingMaxDur to 300

;============ Balancing ===============
set almQ.bArtifactsUnlimited to 1
set almQ.fGlobalMagicSpeedMult to 1.1
set almQ.fGlobalMagicDamageMult to 0.80
set almQ.fGlobalMagicCostMult to 1.0
set almQ.fTargetCostMult to 1.0
set almQ.fElementalShieldDamageMult to 0.0
set almQ.fCHMLCap to 99
set almQ.fRSMACap to 85
set almQ.fREDGCap to 85
set almQ.fRFLCCap to 85

;============ Technical ===============
set almQ.bDisableALMMessages to 0
set almQ.bDebug to 0