;This INI file contains advanced configuration variables, intended to be used by experienced users.
;By default this file does nothing. Uncommenting a line below will override the setting in the mod.

	set almQ.fRainFireMult to 0.85
	set almQ.fRainFrostMult to 1.00
	set almQ.fRainShockMult to 1.15
	set almQ.fSnowFireMult to 0.85
	set almQ.fSnowFrostMult to 1.15
	set almQ.fSwimFireMult to 0.85
	set almQ.fSwimFrostMult to 1.15
	set almQ.fSwimShockMult to 1.15
	set almQ.fOblivionFireMult to 1.15

;	set almQ.fElementalRecoilChanceBase to 25
;	set almQ.fElementalRecoilSkillMult to 0.5
;	set almQ.fElementalImpactChanceBase to 10
;	set almQ.fElementalImpactSkillMult to 0.6

	set almQ.fMagicSneakAttackTouchNoviceMult to 1.0
	set almQ.fMagicSneakAttackTouchApprenticeMult to 1.50
	set almQ.fMagicSneakAttackTouchJourneymanMult to 2.00
	set almQ.fMagicSneakAttackTouchExpertMult to 2.50
	set almQ.fMagicSneakAttackTouchMasterMult to 3.00
	set almQ.fMagicSneakAttackTargetNoviceMult to 1.0
	set almQ.fMagicSneakAttackTargetApprenticeMult to 1.25
	set almQ.fMagicSneakAttackTargetJourneymanMult to 1.50
	set almQ.fMagicSneakAttackTargetExpertMult to 1.75
	set almQ.fMagicSneakAttackTargetMasterMult to 2.00

;	set almQ.fPerkAlteration25Mult to 1.2
	set almQ.fPerkMysticism25CostMult to 0.85
;	set almQ.fPerkMysticism100Chance to 25
;	set almQ.fPerkIllusion25DamageMult to 0.15
;	set almQ.fPerkRestoration25RegenMult to 1.25
;	set almQ.fPerkRestoration75Mult to 1.25