; Better Enemy Health - Config
; ==========================

; By default, the enemy's magicka and fatigue are not displayed.
; Change this value from 0 to 1 to display them alongside their health.

set dsEHMainQ.iEnableExtraBars to 1

; By default, the enemy's level is shown along with their name. Change this value from 0 to 1
; to not show their level.

set dsEHMainQ.iDisableLevel to 0

; By default, a numeric value of the enemy's health will be displayed on the health bar.
; Change this value from 0 to 1 to disable it.

set dsEHMainQ.iDisableTextAV to 0

; By default, the enemy's health will show when they target you or when you hit them.
; Change this value from 0 to 1 to have it appear only when you hit them.

set dsEHMainQ.iVisibility to 1

; By default, the vanilla "arc" bar is left untouched.
; Change this value from 0 to 1 to disable it.

set dsEHMainQ.iDisableVEH to 1

; ==============================================
; Northern UI Skins
; ==============================================

; If using the "Oblivion Style" Theme for NorthernUI, change this value from 0 to 1 to
; use the respective textures.

set dsEHMainQ.iOblivionTheme to 0

; If using the "Imperial Theme" for NorthernUI, change this value from 0 to 1 to
; use the respective textures.

set dsEHMainQ.iImperialTheme to 1

; If using the "Coffee UI" Theme for NorthernUI, change this value from 0 to 1 to
; use the respective textures.

set dsEHMainQ.iCoffeeTheme to 0