; ================================
; Delay DLC Start configurable variables.
; Used by DelayDLCStartCMScript.
; You can tailor each DLC's requirements to allow it to start.
; All but one have location requirements.
; One has a proximity requirement.
; You can choose to ignore each location and distance requirement.
; Set faction rank requirements to -1 so rank doesn’t matter
; If any value is out of the acceptable range, you get a warning so you can fix it.
; ================================

; *** Maximum Skill Level ***
; Set to another value if you use a mod that raises maximum skill levels (100 to X).
; Used only for error checking.
Set DelayDLCStartCM.MaxSkillLevel to 200 ; default 100


; *** Shivering Isles ***
; 1) Minimum level to start the DLC (1 to X).
; 2) Player must be in the Bravil worldspace  (0 = ignore, 1=check).

Set DelayDLCStartCM.ShiveringMinLevel to 15 ; default 20
Set DelayDLCStartCM.ShiveringCheckLocation to 0 ; default 1


; *** Knights of the Nine ***
; 1) MinimumLevel (1 to X).
; 2) Minimum overall Fame (Fame - Infamy) (0 to X).
; 3) Player is not in the Anvil worldspace, the AnvilCastleCourtyard worldspace,
;     any Anvil cell, and not in the Imperial Dungeon (0 = ignore, 1=check).

Set DelayDLCStartCM.KnightsMinLevel to 10 ; default 15
Set DelayDLCStartCM.KnightsMinOverallFame to 15 ; default 15
Set DelayDLCStartCM.KnightsCheckLocation to 1 ; default 1


; *** Battlehorn Castle (Fighter's Stronghold) ***
; 1) Minimum Fighters Guild rank (0 to 9, -1 to ignore rank requirement).
; 2) Minimum sum of combat skills (0 to X, 700 if 100 is the max per skill).
; 3) Player must be in the Chorrol worldspace (0 = ignore, 1=check).

Set DelayDLCStartCM.BattlehornMinFGRank to 3 ; default 3
Set DelayDLCStartCM.BattlehornMinSkillTotal to 200 ; default 200 (about 29 points in each).
Set DelayDLCStartCM.BattlehornCheckLocation to 0 ; default 1


; *** Frostcrag Spire (Wizard's Tower) ***
; 1) Minimum Mages Guild rank (0 to 9, -1 to ignore rank requirement).
; 2) Minimum sum of magic skills (0 to X, 700 if 100 is the max per skill).
; 3) Player must be in the Bruma worldspace (0 = ignore, 1=check).

Set DelayDLCStartCM.FrostcragMinMGRank to 3 ; default 3
Set DelayDLCStartCM.FrostcragMinSkillTotal to 200 ; default 200 (about 29 points in each).
Set DelayDLCStartCM.FrostcragCheckLocation to 0 ; default 1


; *** Thieves Den (Dunbarrow Cove) ***
; 1) Minimum Thieves Guild rank (0 to 7, -1 to ignore rank requirement).
; 2) Minimum sum of stealth skills (0 to X, 700 if 100 is the max per skill).
; 3) Decide if the door to Black Flag area is disabled or enabled before the DLC starts:
;    0 = door is disabled, it is enabled only when the conditions are met.
;    1 = door is enabled, DLC can start early by finding the door and entering cave.
; 4) Player must be in the Anvil worldspace (0 = ignore, 1=check).

Set DelayDLCStartCM.ThievesDenMinTGRank to 3 ; default 3
Set DelayDLCStartCM.ThievesDenMinSkillTotal to 200 ; default 200 (about 29 points in each).
Set DelayDLCStartCM.ThievesDenAllowEntry to 0 ; default 0
Set DelayDLCStartCM.ThievesDenCheckLocation to 0 ; default 1


; *** Deepscorn Hollow (Vile Lair) ***
; 1.1) Minimum Dark Brotherhood rank (0 to 7, -1 to ignore rank requirement).
; OR
; 1.2) Minimum days as a vampire (0 to X).
; AND
; 2) Minimum Infamy (0 to X).
; 3) Player must be in the Leyawiin worldspace (0 = ignore, 1=check).

Set DelayDLCStartCM.DeepscornMinDBRank to 3 ; default 3
Set DelayDLCStartCM.DeepscornMinVampireDays to 0 ; default 7
Set DelayDLCStartCM.DeepScornMinInfamy to 10 ; default 10
Set DelayDLCStartCM.DeepscornCheckLocation to 0 ; default 1


; *** Horse Armor ***
; 1) Minimum level (1 to X).
; 2) Minimum gold (0 to X).
; 3) Minimum Fame (0 to X).
; 4) Player must be in the Talos Plaza District (0 = ignore, 1=check).

Set DelayDLCStartCM.HorseArmorMinLevel to 4 ; default 4
Set DelayDLCStartCM.HorseArmorMinGold to 2000 ; default 2000
Set DelayDLCStartCM.HorseArmorMinFame to 4 ; default 4
Set DelayDLCStartCM.HorseArmorCheckLocation to 1 ; default 1


; *** Mehrunes Razor ***
; 1) Minimum level (1 to X).
; 2) Minimum Infamy (0 to X).
; 3) Player must be in the Elven Gardens District (0 = ignore, 1=check).

Set DelayDLCStartCM.MehrunesMinLevel to 10 ; default 10
Set DelayDLCStartCM.MehrunesMinInfamy to 0 ; default 10
Set DelayDLCStartCM.MehrunesCheckLocation to 1 ; default 1


; *** The Orrery ***
; 1) Minimum Mages Guild rank (0 to 9, -1 to ignore rank requirement).
; 2) Player is within certain distance to Bothiel at the Arcane University (50 to X).
;    Smaller number means you must be closer to her to get the note.
;    50 is right next to her.
; 3) Check the distance (0 = ignore, 1=check).
; 4) If distance check is off, Player must be in the Arcane University.
Set DelayDLCStartCM.OrreryMinMGRank to 1 ; default 1
Set DelayDLCStartCM.OrreryMaxDistBothiel to 200 ; default 200
Set DelayDLCStartCM.OrreryCheckDistance to 0 ; default 1