; Advanced Ini file for Display Skill Perk Effects
; 
; This file must be in Oblivio/Data/Ini if you want to use it.
; This is only needed if you want to override some of the perk descriptions
; To override one, set the override value to 1, remove the ; at the beginning of the 
; next line (set lSPDMainQuest.Perks*) and enter the text you want
; Examples are vanilla default values; Variables are not possible in overrides
; 
; Important:
; Make sure to not use quotation marks (") in the text. Use %q instead.
; Make sure to not use single quotation marks. Use %% instead. 
; Special characters will most likely not work.
; %r is a new line. Perk texts should start with %r%r to leave some space
; between skill description and perk texts.
; Lines can't be longer than 512 characters.


; Combat

set lSPDMainQuest.OverrideArmorer to 0
;set lSPDMainQuest.PerksArmorer to Sv_construct "%r%rNovice: Hammers break easily.%r%rApprentice: Hammers last twice as long.%r%rJourneyman: Can repair magic items.%r%rExpert: Can repair to 125%%.%r%rMaster: Never breaks repair hammers."

set lSPDMainQuest.OverrideAthletics to 1
set lSPDMainQuest.PerksAthletics to Sv_construct "%r%rNovice: Fatigue regenerates 0%% faster while running.%r%rApprentice: Fatigue regenerates 25%% faster while running. No longer require a minimum amount of fatigue to light attack.%r%rJourneyman: Fatigue regenerates 50%% faster while running.%r%rExpert: Fatigue regenerates 75%% faster while running.%r%rMaster: Fatigue regenerates 100%% faster while running." 

set lSPDMainQuest.OverrideBlade to 1
set lSPDMainQuest.PerksBlade to Sv_construct "%r%rNovice: Basic Power Attack (2.5x damage).%r%rApprentice: Standing power attacks deal 20%% more damage and inflict bleeding damage over time.%r%rJourneyman: Sideways power attacks cleave through multiple enemies.%r%rExpert: Backwards power attacks disarm power attacking enemies.%r%rMaster: Forwards power attacks instantly kill enemies at 30%% health or lower."

set lSPDMainQuest.OverrideBlock to 1
set lSPDMainQuest.PerksBlock to Sv_construct "%r%rNovice: Can execute a timed block within 0.3s, preventing all weapon damage.%r%rApprentice: Blocking no longer fatigues you.%r%rJourneyman: Blocking no longer damages your weapon or shield. Bashing fatigues enemies.%r%rExpert: Bashing knocks down enemies that are power attacking.%r%rMaster: Timed blocks have a 50%% chance to disarm the attacker."

set lSPDMainQuest.OverrideBlunt to 1
set lSPDMainQuest.PerksBlunt to Sv_construct "%r%rNovice: Basic Power Attack (2.5x damage).%r%rApprentice: Standing Power attacks shatter enemy armor.%r%rJourneyman: Sideways power attacks disorient enemies, making them stagger 50%% more, or launch them back if already affected.%r%rExpert: Backwards power attacks cripple enemies, draining their strength, speed, and agility.%r%rMaster: Forward power attacks spend all of your remaining fatigue to deal bonus armor piercing damage."

set lSPDMainQuest.OverrideHandToHand to 1
set lSPDMainQuest.PerksHandToHand to Sv_construct "%r%rNovice: Basic Power Attack (2.5x damage).%r%rApprentice: Standing Unarmed power attacks are 20%% stronger and deal bonus armor-piercing damage to foes below 20%% fatigue.%r%rJourneyman: Sideways unarmed power attacks disarm enemies with low fatigue.%r%rExpert: Backwards unarmed power attacks knockback enemies with low fatigue.%r%rMaster: Forwards Unarmed power attacks paralyze enemies with low fatigue."

set lSPDMainQuest.OverrideHeavyArmor to 1
set lSPDMainQuest.PerksHeavyArmor to Sv_construct "%r%rNovice: Heavy armor degrades rapidly (150%% rate).%r%rApprentice: Suffer only 2/3rds the normal fatigue penalty from your armor.%r%rJourneyman: Gain an additional 35%% resistance to stagger.%r%rExpert: Suffer only 1/3rd the fatigue penalty from armor weight.%r%rMaster: Attacks have a chance to recoil off your armor."



; Magic

set lSPDMainQuest.OverrideAlchemy to 1
set lSPDMainQuest.PerksAlchemy to Sv_construct "%r%rNovice: Mix basic potions and poisons.%r%rApprentice: Mix potions from up to three ingredients. Poisons last one additional hit.%r%rJourneyman: Mix potions from up to four ingredients. Learn first two effects. Gather twice as many ingredients.%r%rExpert: Mixed potions lose all negative effects. Learn first three effects. Poisons last one additional hit.%r%rMaster: Mix twice as many potions. Learn all effects. Mix potions from a single ingredient."

set lSPDMainQuest.OverrideAlteration to 0
;set lSPDMainQuest.PerksAlteration to Sv_construct "%r%rNovice: Able to cast Novice level spells.%r%rApprentice: Able to cast Apprentice level spells.%r%rJourneyman: Able to cast Journeyman level spells.%r%rExpert: Able to cast Expert level spells.%r%rMaster: Able to cast all spells."

set lSPDMainQuest.OverrideConjuration to 0
;set lSPDMainQuest.PerksConjuration to Sv_construct "%r%rNovice: Able to cast Novice level spells.%r%rApprentice: Able to cast Apprentice level spells.%r%rJourneyman: Able to cast Journeyman level spells.%r%rExpert: Able to cast Expert level spells.%r%rMaster: Able to cast all spells."

set lSPDMainQuest.OverrideDestruction to 0
;set lSPDMainQuest.PerksDestruction to Sv_construct "%r%rNovice: Able to cast Novice level spells.%r%rApprentice: Able to cast Apprentice level spells.%r%rJourneyman: Able to cast Journeyman level spells.%r%rExpert: Able to cast Expert level spells.%r%rMaster: Able to cast all spells."

set lSPDMainQuest.OverrideMysticism to 0
;set lSPDMainQuest.PerksMysticism to Sv_construct "%r%rNovice: Able to cast Novice level spells.%r%rApprentice: Able to cast Apprentice level spells.%r%rJourneyman: Able to cast Journeyman level spells.%r%rExpert: Able to cast Expert level spells.%r%rMaster: Able to cast all spells."

set lSPDMainQuest.OverrideRestoration to 0
;set lSPDMainQuest.PerksRestoration to Sv_construct "%r%rNovice: Able to cast Novice level spells.%r%rApprentice: Able to cast Apprentice level spells.%r%rJourneyman: Able to cast Journeyman level spells.%r%rExpert: Able to cast Expert level spells.%r%rMaster: Able to cast all spells."

set lSPDMainQuest.OverrideIllusion to 0 
;set lSPDMainQuest.PerksIllusion to Sv_construct "%r%rNovice: Able to cast Novice level spells.%r%rApprentice: Able to cast Apprentice level spells.%r%rJourneyman: Able to cast Journeyman level spells.%r%rExpert: Able to cast Expert level spells.%r%rMaster: Able to cast all spells."


; Stealth

set lSPDMainQuest.OverrideAcrobatics to 1
set lSPDMainQuest.PerksAcrobatics to Sv_construct "%r%rNovice: Cannot attack while jumping or falling.%r%rApprentice: Normal attack while jumping or falling. %r%rJourneyman: Power attack while jumping or falling. Dodge by holding block while pressing jump.%r%rExpert:Jumping and Dodging cost less fatigue..%r%rMaster: Water Jump ability, can jump off the surface of water."

set lSPDMainQuest.OverrideLightArmor to 1
set lSPDMainQuest.PerksLightArmor to Sv_construct "%r%rNovice: Light armor degrades rapidly (150%% rate).%r%rApprentice: Weight penalizes fatigue regeneration half as much when you aren't wearing heavy armor.%r%rJourneyman: Gain 40%% resistance to poison, disease, paralysis, and petrification.%r%rExpert: Suffer no fatigue penalty from worn light armor.%r%rMaster: All incoming attacks have a chance to be dodged completely." 

set lSPDMainQuest.OverrideMarksman to 1
set lSPDMainQuest.PerksMarksman to Sv_construct "%r%rNovice: Fatigue loss when holding a drawn bow (3/s).%r%rApprentice: Less fatigue loss when holding a drawn bow (2/s).%r%rJourneyman: Zoom and slow time by holding block. Less fatigue loss when holding a drawn bow (1/s).%r%rExpert: Chance of knockdown on hit. Zoom and time slow increased. No fatigue loss when holding a drawn bow.%r%rMaster: Chance of paralysis on hit."

set lSPDMainQuest.OverrideMercantile to 1
set lSPDMainQuest.PerksMercantile to Sv_construct "%r%rNovice: Sell items at reduced price.%r%rApprentice: Chance to find bonus treasure based on Mercantile. Spellmaking is 35%% cheaper.%r%rJourneyman: Merchants receive additional gold. Repairs are 35%% cheaper.%r%rExpert: Invest in a shop to permanently increase the shop's available gold. Recharging is 35%% cheaper.%r%rMaster: All merchants have 500 more gold. Barter at 100%% ratio. Services are 50%% cheaper."

set lSPDMainQuest.OverrideSecurity to 1
set lSPDMainQuest.PerksSecurity to Sv_construct "%r%rNovice: When you fail to pick a lock, you break a lockpick.%r%rApprentice: When you fail to pick a lock, you have 50%% chance to keep your lockpick.%r%rJourneyman: You find more gold in picked chests.%r%rExpert: You receive a wax copy of a picked lock's key, if one exists.%r%rMaster: You can pick locks in the open without being noticed."

set lSPDMainQuest.OverrideSneak to 0
;set lSPDMainQuest.PerksSneak to Sv_construct "%r%rNovice: Sneak damage: Melee 4.0x, Bow 2.0x.%r%rApprentice: Sneak damage: Melee 6.0x , Bow 3.0x.%r%rJourneyman: Sneak damage: Melee 6.0x , Bow 3.0x. No penalty for booth weight.%r%rExpert: Sneak damage: Melee 6.0x , Bow 3.0x. No penalty for running.%r%rMaster: Sneak damage: Melee 6.0x , Bow 3.0x. Sneak attacks ignore armor."

set lSPDMainQuest.OverrideSpeechcraft to 1
set lSPDMainQuest.PerksSpeechcraft to Sv_construct "%r%rNovice: Can receive gifts & hints. Can tame 1 animal.%r%rApprentice: Get hints for best & worst options. Can tame 2 animals.%r%rJourneyman: Minimum disposition gain for success increased. Can tame 3 animals.%r%rExpert: Total disposition loss is reduced. Can tame 4 animals.%r%rMaster: Recieve better & more unique gifts based on class of person you talk to. Can tame 5 animals."


; Custom Skills

set lSPDMainQuest.OverrideUnarmored to 0
;set lSPDMainQuest.PerksUnarmored to Sv_construct "%r%rAll effects only apply when fully unarmored.%r%rNovice: No armor bonus.%r%rApprentice: Armor bonus of 10.%r%rJourneyman: Armor bonus of 20. Speed bonus of 10.%r%rExpert: Armor bonus of 20. Speed bonus of 10. Deal more Hand to Hand damage.%r%rMaster: Armor bonus of 20. Speed bonus of 10. 25%% chance to evade attacks."

set lSPDMainQuest.OverrideEnchanting to 1
set lSPDMainQuest.PerksEnchanting to Sv_construct "%r%rNovice: Can create enchantments.%r%rApprentice: Enchantments on weapons return a small amount of charge after use.%r%rJourneyman: Enchanting armor and clothing costs less.%r%rExpert: Weapons recharge slowly on their own.%r%rMaster: Place additional constant effects on self enchanted apparel."

set lSPDMainQuest.OverridePickpocket to 1
set lSPDMainQuest.PerksPickpocket to Sv_construct "%r%rNovice: Can pickpocket humanoid npcs while crouching.%r%rApprentice: Pickpocketing keys, gold, low weight & value items, or from sleeping targets never fails while undetected.%r%rJourneyman: Poisons that you reverse-pickpocket on non-essential actors are applied to them.%r%rExpert: Stolen items you carry don't add to your encumbrance.%r%rMaster: : You can pickpocket equipped items from non-essential targets while undetected by them."