; Dynamic Map base.ini
; =====================
;
; Version: 2.1
; Author: Ole Boe / TheNiceOne


; See http://cs.elderscrolls.com/constwiki/index.php/OnKeyDown for numbers to use when selecting zoom keys
set tnoDM.zoomIn to 264
set tnoDM.zoomOut to 265
set tnoDM.zoomReset to 4

; Set visibility of zoom buttons
; 0: Hide buttons
; 1: Only display buttons when the mouse is pointing at them
; 2: Always display buttons
set tnoDM.zoom_btn_visible to 2

; Set position of zoom buttons
; 0 is left / top, 100 is right / bottom. Decimals can be used
set tnoDM.zoom_btn_x to 0
set tnoDM.zoom_btn_y to 100

; Default zoom. Vanilla is 200, and DarN UI is 120.
set tnoDM.defaultZoom to 100

; Zoom steps. When zooming in/out, the zoom will be multiplied/divided by (zoomStep + 1).
set tnoDM.zoomStep to 0.25

; Debug mode. Set to 1 (or 2) for debug output
set tnoDM.debug to 0
 
; Display all map components regardless of mods
set tnoDM.display_all to 0
 
 