; Dynamic Map.ini for Terrain Map style
; =====================
;
; Version: 2.1
; Author: Ole Boe / TheNiceOne


 
; Init Tamriel worldspace map
set tnoDM.mod to sv_Construct "Oblivion.esm"
set tnoDM.fid to sv_Construct "00003C"
; set tnoDM.x_offset to 126
; set tnoDM.y_offset to 301
; set tnoDM.zoom to 1
set tnoDM.nw_x to -59
set tnoDM.nw_y to 47
set tnoDM.se_x to 59
set tnoDM.se_y to -53
set tnoDM.w to 2975
set tnoDM.h to 2525
SetStage tnoDM 10

set tnoDM.mod to sv_Construct "Unique Landscapes.esp"
set tnoDM.img to sv_Construct "xulFallenleafEverglade.esp"
set tnoDM.x to 1126
set tnoDM.y to 1225
set tnoDM.w to 200
set tnoDM.h to 125
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "ElsweyrAnequina.esp"
set tnoDM.x to 869
set tnoDM.y to 1180
set tnoDM.w to 1130
set tnoDM.h to 1600
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "Valenwood Improved.esp"
set tnoDM.x to 0
set tnoDM.y to 0
set tnoDM.w to 1499
set tnoDM.h to 2925
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "Unique Landscapes.esp"
set tnoDM.img to sv_Construct "xuldarkforest.dds"
set tnoDM.x to 1700
set tnoDM.y to 1049
set tnoDM.w to 150
set tnoDM.h to 200
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "Unique Landscapes.esp"
set tnoDM.img to sv_Construct "xulStendarrValley.dds"
set tnoDM.x to 1350
set tnoDM.y to 224
set tnoDM.w to 175
set tnoDM.h to 125
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "Unique Landscapes.esp"
set tnoDM.img to sv_Construct "xulTheHeath.dds"
set tnoDM.x to 300
set tnoDM.y to 999
set tnoDM.w to 200
set tnoDM.h to 100
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "Unique Landscapes.esp"
set tnoDM.img to sv_Construct "xulEntiusGorge.dds"
set tnoDM.x to 2400
set tnoDM.y to 999
set tnoDM.w to 125
set tnoDM.h to 175
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "Unique Landscapes.esp"
set tnoDM.img to sv_Construct "xulColovianHighlands_EV.dds"
set tnoDM.x to 675
set tnoDM.y to 524
set tnoDM.w to 200
set tnoDM.h to 225
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "Unique Landscapes.esp"
set tnoDM.img to sv_Construct "xulChorrolHinterland.dds"
set tnoDM.x to 975
set tnoDM.y to 524
set tnoDM.w to 225
set tnoDM.h to 205
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "Unique Landscapes.esp"
set tnoDM.img to sv_Construct "xulBeachesOfCyrodiilLostCoast.dds"
set tnoDM.x to 75
set tnoDM.y to 1074
set tnoDM.w to 175
set tnoDM.h to 375
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "Unique Landscapes.esp"
set tnoDM.img to sv_Construct "xulBravilBarrowfields.dds"
set tnoDM.x to 1700
set tnoDM.y to 1324
set tnoDM.w to 425
set tnoDM.h to 300
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "Unique Landscapes.esp"
set tnoDM.img to sv_Construct "xulLushWoodlands.dds"
set tnoDM.x to 1175
set tnoDM.y to 399
set tnoDM.w to 425
set tnoDM.h to 325
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "Unique Landscapes.esp"
set tnoDM.img to sv_Construct "xulAncientYews.dds"
set tnoDM.x to 1926
set tnoDM.y to 700
set tnoDM.w to 225
set tnoDM.h to 325
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "Unique Landscapes.esp"
set tnoDM.img to sv_Construct "xulAncientRedwoods.dds"
set tnoDM.x to 1075
set tnoDM.y to 724
set tnoDM.w to 300
set tnoDM.h to 350
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "Unique Landscapes.esp"
set tnoDM.img to sv_Construct "xulCloudtopMountains.dds"
set tnoDM.x to 800
set tnoDM.y to 199
set tnoDM.w to 325
set tnoDM.h to 300
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "Unique Landscapes.esp"
set tnoDM.img to sv_Construct "xulArriusCreek.dds"
set tnoDM.x to 1999
set tnoDM.y to 348
set tnoDM.w to 450
set tnoDM.h to 350
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "Unique Landscapes.esp"
set tnoDM.img to sv_Construct "xulPatch_AY_AC.dds"
set tnoDM.x to 1974
set tnoDM.y to 648
set tnoDM.w to 100
set tnoDM.h to 125
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "Unique Landscapes.esp"
set tnoDM.img to sv_Construct "xulRollingHills_EV.dds"
set tnoDM.x to 1850
set tnoDM.y to 599
set tnoDM.w to 150
set tnoDM.h to 150
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "Unique Landscapes.esp"
set tnoDM.img to sv_Construct "xulPantherRiver.dds"
set tnoDM.x to 2150
set tnoDM.y to 1449
set tnoDM.w to 500
set tnoDM.h to 275
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "Unique Landscapes.esp"
set tnoDM.img to sv_Construct "xulRiverEthe.dds"
set tnoDM.x to 850
set tnoDM.y to 724
set tnoDM.w to 225
set tnoDM.h to 575
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "Unique Landscapes.esp"
set tnoDM.img to sv_Construct "xulBrenaRiverRavine.dds"
set tnoDM.x to 200
set tnoDM.y to 699
set tnoDM.w to 435
set tnoDM.h to 350
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "Unique Landscapes.esp"
set tnoDM.img to sv_Construct "xulImperialIsle.dds"
set tnoDM.x to 1476
set tnoDM.y to 649
set tnoDM.w to 350
set tnoDM.h to 325
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "Unique Landscapes.esp"
set tnoDM.img to sv_Construct "xulBlackwoodForest.dds"
set tnoDM.x to 2100
set tnoDM.y to 2074
set tnoDM.w to 225
set tnoDM.h to 225
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "Unique Landscapes.esp"
set tnoDM.img to sv_Construct "xulCheydinhalFalls.dds"
set tnoDM.x to 2150
set tnoDM.y to 549
set tnoDM.w to 200
set tnoDM.h to 275
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "Unique Landscapes.esp"
set tnoDM.img to sv_Construct "xulAspenWood.dds"
set tnoDM.x to 2200
set tnoDM.y to 1074
set tnoDM.w to 175
set tnoDM.h to 225
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "Unique Landscapes.esp"
set tnoDM.img to sv_Construct "xulSkingradOutskirts.dds"
set tnoDM.x to 1000
set tnoDM.y to 1074
set tnoDM.w to 260
set tnoDM.h to 125
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "Unique Landscapes.esp"
set tnoDM.img to sv_Construct "xulSnowdale.dds"
set tnoDM.x to 1549
set tnoDM.y to 98
set tnoDM.w to 525
set tnoDM.h to 325
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "Unique Landscapes.esp"
set tnoDM.img to sv_Construct "xulCliffsOfAnvil.dds"
set tnoDM.x to 299
set tnoDM.y to 1473
set tnoDM.w to 225
set tnoDM.h to 100
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "bartholm.esp"
set tnoDM.x to 2212
set tnoDM.y to 1511
set tnoDM.w to 111
set tnoDM.h to 111
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "Better Cities Full.esp"
set tnoDM.or_mod to sv_Construct "Better Cities Full - B&M Edition.esp"
set tnoDM.img to sv_Construct "Better Cities Anvil.dds"
set tnoDM.zoom to 0.25
set tnoDM.x to 226
set tnoDM.y to 1357
set tnoDM.w to 535
set tnoDM.h to 481
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "Better Cities Full.esp"
set tnoDM.img to sv_Construct "Better Cities Bravil.dds"
set tnoDM.zoom to 0.25
set tnoDM.x to 1817
set tnoDM.y to 1378
set tnoDM.w to 499
set tnoDM.h to 431
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "Better Cities Full - B&M Edition.esp"
set tnoDM.img to sv_Construct "Better Cities Bravil B&M.dds"
set tnoDM.zoom to 0.25
set tnoDM.x to 1817
set tnoDM.y to 1374
set tnoDM.w to 623
set tnoDM.h to 535
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "Better Cities Full.esp"
set tnoDM.or_mod to sv_Construct "Better Cities Full - B&M Edition.esp"
set tnoDM.img to sv_Construct "Better Cities Bruma.dds"
set tnoDM.zoom to 0.25
set tnoDM.x to 1585
set tnoDM.y to 263
set tnoDM.w to 319
set tnoDM.h to 319
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "Better Cities Full.esp"
set tnoDM.or_mod to sv_Construct "Better Cities Full - B&M Edition.esp"
set tnoDM.img to sv_Construct "Better Cities Cheydinhal.dds"
set tnoDM.zoom to 0.25
set tnoDM.x to 2165
set tnoDM.y to 581
set tnoDM.w to 319
set tnoDM.h to 399
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "Better Cities Full.esp"
set tnoDM.or_mod to sv_Construct "Better Cities Full - B&M Edition.esp"
set tnoDM.img to sv_Construct "Better Cities Chorrol.dds"
set tnoDM.zoom to 0.25
set tnoDM.x to 1026
set tnoDM.y to 575
set tnoDM.w to 459
set tnoDM.h to 339
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "Better Cities Full.esp"
set tnoDM.or_mod to sv_Construct "Better Cities Full - B&M Edition.esp"
set tnoDM.img to sv_Construct "Better Cities Leyawiin.dds"
set tnoDM.zoom to 0.25
set tnoDM.x to 1975
set tnoDM.y to 2023
set tnoDM.w to 559
set tnoDM.h to 699
SetStage tnoDM 20

set tnoDM.mod to sv_Construct "Better Cities Full.esp"
set tnoDM.or_mod to sv_Construct "Better Cities Full - B&M Edition.esp"
set tnoDM.img to sv_Construct "Better Cities Skingrad.dds"
set tnoDM.zoom to 0.25
set tnoDM.x to 1026
set tnoDM.y to 1125
set tnoDM.w to 299
set tnoDM.h to 399
SetStage tnoDM 20
