; Enhanced Hotkeys.ini
; =====================
;
; Version: 2.3.1
; Author: Ole Boe / TheNiceOne
; 
; The settings are read each time a game is loaded with this mod activated
; If nothing else is written, 0=disabled and 1=enabled


; Enables or disables debug messages. 0: Disable, 1: Enable
set tnoEH.debug to 0


;=================== Hotkey menu layout ===================

; Note that keysPerRow x keysPerColumn is the number of available hotkeys per wheel, and cannot be more than 40.

; Number of hotkeys displayed per row (default: 8)
set tnoEH.keysPerRow to 8

; Number of hotkey columns (default: 5)
set tnoEH.keysPerColumn to 5

; Set whether to read keyfile that holds initial key bindings only when starting a new game (or first time after installing EH),
; or whether to read it each time a savegame is loaded.
; The latter is preferable if you like to change key bindings in ini file, but you can then not do changes manually ingame.
; 0: Only read when starting a new game, 1: Read each savegame load
set tnoEH.always_read_keyfile to 1

; Size of hotkey icons. 100 is full size (default: 100)
set tnoEH.zoomFactor to 100

; Set screen position of hotkey menu
; 0: top
; 1: middle
; 2: bottom
; 3: top right
; 4: middle right
; 5: bottom right
set tnoEH.wheelPosition to 1

; Size of fonts (if using MenuQue). 
; 10, 12 or 14 are legal values. If 0 (or not having MenuQue), standard Oblivion font 3 will be used.
set tnoEH.fontSize to 12

; Vertical adjustment of fonts in the hotkey grid (default 7)
set tnoEH.fontAdjustment to 7


;=================== Wheels (hotkey sets) ===================

; Set whether wheel modifier keys are sticky
; If enabled, only tnoEH.wheel_1 (see below) is used to switch between wheels.
; Tapping tnoEH.wheel_1 will switch to next wheel.
; 0: Disable, a wheel modifier key must be held down to use that wheel
; 1: Enable with one key to scroll between all the different wheels
; 2: As 1, with a Message each time the wheel changes
; 3: Enable, with one key for each wheel
; 4: As 3, with a Message each time the wheel changes
set tnoEH.stickyWheel to 0

; Modifier keys for wheels. Wheel 0's modifier is only used for sticky wheels
; Set to 0 if you don't want to use a wheel.
; If enabling stickyWheel in mode 1/2, only tnoEH.wheel_0 is used as a key. The others use 0 to disable, and any non-null value to enable
; If disabling stickyWheel, each wheel except wheel_0 needs a unique modifier key.
; See Key modifiers section below for values
set tnoEH.wheel_0 to 56		; Not used unless stickyWheel is enabled
set tnoEH.wheel_1 to 56		
set tnoEH.wheel_2 to 0
set tnoEH.wheel_3 to 0


;=================== Wheels HUD icon ===================

; Set up HUD Wheel icon (only applicable if stickyWheel is enabled)

; Number of seconds the wheel icon will be lit up after a wheel switch.
; Setting it to 0 disables the wheel completely.
; Setting it to -1 means no timeout, i.e. fully visible all the time
set tnoEH.wheelIconTimeout to 4

; Opaqueness of the lit up wheel icon. (default 200)
; 255 (max) is completely opaque. 0 is invisible.
set tnoEH.wheelIconAlphaMax to 200

; Opaqueness of the wheel icon when no longer lit up
; Set it to 0 to hide the wheel after lit up period
; 255 (max) is completely opaque. 0 is invisible.
set tnoEH.wheelIconAlphaMin to 100

; Wheel icon size (default 24)
set tnoEH.wheelIconSize to 24

; Wheel icon position (default 16, 48)
set tnoEH.wheelIconX to 16
set tnoEH.wheelIconY to 48


;=================== Mouse button behaviour ===================

; Enable or disable the use of the mouse wheel to cycle through hotkeyed items
; Possible values are
; 0: Disable mousewheel support
; 1: The mouse wheel will always cycle through the last cycler hotkey you have tapped
; 2: The mouse wheel will always cycle through one specific hotkey, determined by mouseWheelHotkey below
set tnoEH.mouseWheelMode to 0

; Set default direction for mouse cycling. 0 means that moving mouse wheel up cycles forwards and down backwards. 1 switches the direction.
set tnoEH.mouseWheelDirection to 0

; Only applicable if mouseWheelMode is 2. Determines the hotkey (0-39) that the mouse wheel cycles.
; Note that this works for the currently active wheel.
set tnoEH.mouseWheelHotkey to 0

; Set whether mouse buttons bound to hotkeys, will need a special key pressed, to function as hotkey ingame
; Only the three main mouse buttons are restricted this way, additional mouse buttons always work, if bound to a hotkey
; Possible values are 
; 0: Mouse buttons will always work as hotkeys ingame
; 1: Only work if mouseBtnKey (see below) is pressed
; 2: Only work if mouseBtnKey or one of the wheel selector keys are held down 
set tnoEH.mouseBtnNeedModifier to 1

; Set whether the normal use of a mouse button is disabled when mouseBtnKey or or one of the wheel selector keys are held down 
; Only the three main mouse buttons are disabled this way, additional mouse buttons are not affected
; Mouse buttons are not disabled unless you had them bound to hotkeys when loading last save
; Possible values are 
; 0: Mouse buttons' normal effect is never disabled
; 1: Mouse buttons' normal effect is disabled when mouseBtnKey is pressed
; 2: Mouse buttons' normal effect is disabled when mouseBtnKey or one of the wheel selector keys are held down 
set tnoEH.mouseBtnDisableNormal to 1



;=================== Key modifiers ===================

; All settings below that reuire modifier keys use the following values
; Left Shift	42
; Right Shift	54
; Left Control	29
; Right Control	157
; Left Alt		56
; Right Alt		184
; Q-P			16-25
; A-L			30-38
; Z-M			44-50

; Modifier key used for controlling if a cycler hotkey activates objects in normal order, or in backwards order
; Default: 0 - disabled
set tnoEH.cycleBackKey to 0

; Modifier key used for cycling the item icons to see the different items bound to one key (cycler key)
; Set to 0, if this is to be default behaviour (without any modifier key) when clicking on a key icon
; Default: Hold down left ctrl (29) to cycle item icons.
set tnoEH.cycleKey to 29

; Modifier key used for switching between different key modes (normal - auto cast for single spells, cycler type for multiple items)
; Set to 0, if this is to be default behaviour when clicking on a key icon. Don't set both this and cycle key to 0!
; Default: Cycle hotkey mode without any key (0)
set tnoEH.modeKey to 0

; Modifier key used for appending items to one hotkey, by clicking on an item in the inventory/spell lists
; See also addItemMode just below
; Default left control (29)
set tnoEH.addKey to 29

; If addItemMode is 0, clicking on an item in the inventory/spell menu replaces the current content of the selected hotkey 
; with the one you click, while doing it with addKey (left control) down appends the new item to the existing items.
; If addItemMode is 1, this is reversed so that merely clicking appends the item while control-clicking replaces the current items.
set tnoEH.addItemMode to 1

; Modifier key used for clicking on a hotkey's keyboard name, in order to switch the key to use
; Set to 0, to allow keyboard configuration without any modifier key
; Default: Hold down left ctrl (29) to change keyboard configuration
set tnoEH.changeKeyboardKey to 29

; Modifier key used for enabling main thre mouse buttons as hotkeys (see above)
; Default: Hold down X (45) to use mouse buttons as hotkeys
set tnoEH.mouseBtnKey to 45

;=================== Misc settings ===================


; Enable fast spell switching during multicast. When enabled, the mod will switch back to the old active spell between each cast
; If disabled, the old active spell will not be activated until the multi cast sequence is completed. 
set tnoEH.fastSpellIconSwitching to 1


; Display (un-)equip messages for weapons, arrows, armor and clothing, and activation message for spells.
set tnoEH.equipMessages to 1

; Display Cast messages when auto/multi-casting spells/scrolls
; 0: No cast message, 1: Display message when only casting 1 spell (auto-cast), 2: Display message for all.
set tnoEH.autoCastMessages to 1

; Delay (in seconds) before (un-)equip or cast messages are displayed.
; If a new message is created before the delay has passed, the 1st message is discarded and delay reset
; By having a non-zero delay, you will only see the last message when tapping a cycler key multiple times
set tnoEH.messageDelay to 0.5


; Settings for people who encounter incompatibilities with magick mods, or with multi-cast:
; Set time (in seconds) to wait before giving up when trying to cast a spell
set tnoEH.castWaitMax to 0.7

; Debug settings for magic mod compatibility. Set delay (in frames) before/after casting spell
set tnoEH.preCastDelay to 0
set tnoEH.postCastDelay to 1

