 ;The codes for keys are DirectX scancodes, which you can lookup here: https://wiki.nexusmods.com/index.php/DirectX_Scancodes_And_How_To_Use_Them
;Setting a key code to 0 will disable it's functionality.

set ExUI.bEnableSpellFavourites to 			1		;Enables or disables Favourite Spells feature. Default: 1 (Enabled)
set ExUI.iKeySpellFavourites to				33		;Key used to bring up spell favourites menu and to add/remove spells from favourites. Default: Q (16)
set ExUI.iKeySpellFavouritesUp to			264		;Key used to scroll spell favourites menu up. Default: Mouse Wheel Up (264)
set ExUI.iKeySpellFavouritesDown to			265		;Key used to scroll spell favourites menu down. Default: Mouse Wheel Down (265)
set ExUI.iSFPosX to							20		;Horizontal position of spell favourites menu, as a percentage of total screen width.
set ExUI.iSFPosY to							65		;Vertical position of spell favourites menu, as a percentage of total screen height.

set ExUI.bEnableCyclingQuicksave to 		1		;Enables or disables Cycling Quicksave feature. Default: 1 (Enabled)
set ExUI.iMaxQuicksaves to 					10		;Maximum number of cycling quicksaves. Default: 10

set ExUI.bEnableExtraHUDInfo to 			1		;Enables or disables Extra HUD Info feature. Default: 1 (Enabled)
set ExUI.bExtraHUDShowIcons to 				1		;Whether or not Extra HUD Info shows icons for magic effects. Default: 1 (Enabled)
set ExUI.iEIPosX to							60		;Horizontal position of Extra HUD info box, as a percentage of total screen width.
set ExUI.iEIPosY to							65		;Vertical position of Extra HUD info box, as a percentage of total screen height.

set ExUI.bEnableQuantityShortcuts to 		1		;Enables or disables keyboard shortcuts for quantity selection menu. Default: 1 (Enabled)
set ExUI.iKeyQuantityOne to					29		;Key used to move only one item in stack. Default: Left Ctrl (29)
set ExUI.iKeyQuantityAll to					42		;Key used to move all items in stack. Default: Left Shift (42)
set ExUI.fQuantityWeightThreshold to		0.01	;If item weight is below this threshold, the function of above key is reversed. Default: 0.01

set ExUI.bEnableKeyboardMenuNavigation to 	1		;Enables or disables keyboard menu navigation in inventory/magic/stats/journal. Default: 1 (Enabled)
set ExUI.bEnableMenuEscape to 				1		;Enables or disables exiting any menu with inventory key. Default: 1 (Enabled)
set ExUI.iKeyContainerSwitch to				56		;Key used to switch between inventory and container. Default: Left Alt (56)
set ExUI.iKeyTakeAll to						19		;Keyboard shortcut for Take All button in container. Default: R (19)

set ExUI.bEnableItemDescriptions to 		1		;Enables or disables descriptions for inventory items. Default: 1 (Enabled)
set ExUI.bEnableSpellDescriptions to 		1		;Enables or disables descriptions for spells. Default: 1 (Enabled)
set ExUI.bShowSpellHostility to 			1		;Show whether or not spell is considered hostile in description. Default: 1 (Enabled)
set ExUI.bShowSpellSilenceImmunity to 		1		;Show whether or not spell is immune to silence in description. Default: 1 (Enabled)
set ExUI.bShowSpellAoE to 					1		;Show whether or not touch spell "explodes with no target" in description. Default: 1 (Enabled)

set ExUI.bEnableBossBars to 				1
set ExUI.bEnableSpellDeletion to 			1
set ExUI.bEnablePerkInfo to 				0
set ExUI.iMaxWaitTime to 					24

;MessageBox Skips (Disabled by default)
set ExUI.bSkipBuy to 		1
set ExUI.bSkipSell to 		1
set ExUI.bSkipGive to 		1
set ExUI.bSkipBuySpell to 	1
set ExUI.bSkipPoison to 	1
