; OSCURO'S OBLIVION OVERHAUL v.1.5.15

; Modified: allexa


; OOO settings. To change the settings, you need to exit the game, make your changes in this file, and then load Oblivion.

; Attention! If you use the "LINK" mod - the settings in the ini-file will be ignored.
; Use the in-game "LINK" menu to adjust configuration settings.  

; Ini parameters
; ==============


; ***GEOMANCY:***
; Geomancy gives you powerful spells that use gems and minerals (i.e., Gold Nuggets) as components. 
; Each gem gives you a different type of spell, while each quality (i.e., Flawed, Perfect) gives you different strengths of the spell. 
; Spells are added and removed automatically, reflecting your inventory.
; You need to read the book "Report on Ayleid Geomancy" before you can cast the spells (it will automatically enable Geomancy, so you don't need to do it yourself).
; Once you've read the book, you can turn Geomancy on and off as you please. 
; default (1 enabled) ;0 disabled
Set OOOOptions.bGeomancy to 0


; ***HARVEST CONTAINERS:***
; The Harvest Containers feature of OOO makes containers appear open  (checked) after you try to access (activate) them. 
; This feature is optional, however.  You can turn off the animating of some or all container types.
; - This Enable/Disable animation of Chests, Cupboards, Desks and Drawers, etc...
; default (1 enabled) ;0 disables animation
Set OOOHC to 1 

; - This Enable/Disable animation of Ayleid chests
; default (1 enabled) ;0 disables animation
Set OOOHCAyleid to 1 

; - This Enable/Disable animation of barrels and Crates
; default (1 enabled) ;0 disables animation
Set OOOHCBarrelsAndCrates to  1 

; - This Enable/Disable animation of Sacks
; default (1 enabled) ;0 disables animation
Set OOOHCSacks to 1

; - This Enable/Disable animation ore vein animation
; default (1 enabled) ;0 disables animation
Set OOOHCVein to 1

; - This Enable/Disable animation of pearl extraction from pearl mollusks.
; default (1 enabled) ;0 disables animation
Set OOOHCClams to 1

; - This will turn off animating containers in player owned houses
; default (1 enabled) ;0 disables animation
Set OOOHCPlayerHouse to	1


; ***DROP LIT TORCHES:***
; DLT allows you to quickly drop your equipped torch to the ground when you draw you weapon for battle.
; !!!- this is useful when you have to fight in dark places.
; The torch you throw will illuminate everything nearby for a while, thereby helping you in battle.
; (disabled by default) ;0 disables DLT, 1 enables
Set OOOOptions.bDLT to 0

; - Do you want a torch hotkey menu item to offer a hassle- and message-free way of equipping and unequipping a torch?
; - Adds a handy "equip torch" item to your inventory for use in the hotkey menu.
; (disabled by default) ;0 disables the hotkey, 1 enables it
Set OOOOptions.bHK to 0

; ***CONTAINER TRAPS:***
; You can turn container traps on and off here, and set them to have some randomization if they are enabled. 
; - Would you like containers to be trapped?  If so, set bTrapped to 1.
; - If you do want traps, would you like to add a random chance for each container that would normally be trapped to not be trapped.  If so, set bTrapped to 2.
; (default "2") ;0 disables traps, 1 enables traps, 2 enables randomization of traps
Set OOOOptions.bTrapped to 0

; ***LOCKBASHING:***
; You can turn Lock Bash Omega on or off. (ability to break locks with a weapon strike)/
; default (1 enables) ;0 disables LBO
Set OOOOptions.bLockBash to 1

; ***Additional respawn settings***
;==================================

;***CLAMS:***
; You can enable or disable the respawn of pearls in pearl clam shells.
; default (1 enabled) ;0 disabled
Set OOOOptions.ClamsRespavn to 1

;***VEIN:***
; You can enable or disable the respawn of silver and gold ore veins.
; default (1 enabled) ;0 disabled
Set OOOOptions.VeinRespavn to 1

;***Roasted Rat:***
; You can turn on or off respawn for "Roasted Rat".
; In the vanilla game, the meat of rats roasted on a fire does not respawn, and with the animation function, "empty sticks over a fire" remain until the end of the game, which is not entirely logical, with a common respawn in dungeons.
; default (1 enabled) ;0 disabled
Set OOOOptions.RoastRatRespavn to 1


; ***Other OOO settings***
;=====================

; ***LIGHT OF DAWN:***
; When you unsheath the Light of Dawn it will burst into flames, like the surface of the sun.
; (enabled by default) ;0 disables sword flames, 1 enables
Set OOOLightOfDawnUseFlame to 1

; ***Combat Locked:***
; Enable/disable warning and blocking of container hacking during combat.
; default (1 enabled) ;0 disabled
LapNoCombatLock to 0

;***Min Lock:***
; Enable/disable warning and blocking of lock picking (if your lock picking level is 40 points lower than the lock level), i.e. adds/removes restrictions for picking depending on the level of the picking skill.
; default (1 enabled) ;0 disabled
LapMinLock to 0 


;***ADVENTURERS:***
; Determines the behavior of NPC Adventurers. This is a player-friendly faction of NPCs that spawn in dungeons and are engaged in hacking and looting various containers.
; default (1) - Adventurers loot all available items from containers.
; when set to (0) - Adventurers will only loot items from the "misc item" category (like in vanilla).
Set OOOAdventures to 1

