; SB ARROW MASTER

; AUTO-EQUIP ARROWS
; Toggles Auto-Equip Arrows On or Off
set SBAMAutoEquipArrowsGlobal to				1 ; 0 Off, 1 On

; Defines When Enchanted Arrows Should be Considered for Auto-Equip
set SBAMAutoEquipArrowsEnchantedGlobal to    	2 ; 0 Always Allow, 1 Never Allow, 2 Only Allow if No Unenchanted Arrows Remain (Default 2).

; BOUND ARROWS
; Toggles Bound Arrows On or Off
set SBAMBoundArrowsGlobal to					1 ; 0 Off, 1 On

; Defines the Damage Done by Bound Arrows
set SBAMBoundArrowsDamageGlobal to				11 ; 11 is 75% of Daedric Arrow damage, Same Ratio as Bound Bow Damage to Daedric Bow Damage (Default 11)

; DENOCK ARROWS
; Toggles Denock Arrows On or Off
set SBAMDenockArrowsGlobal to					1 ; 0 Off, 1 On

; FOCUS SHOT
; Toggles Focus Shot On or Off
set SBAMFocusShotGlobal to					0 ; 0 Off, 1 On

; Percentage of regular gamespeed (default 25%)
set SBAMFocusShotMultiplierGlobal to			100 ; Value betweeen 0 and 100

; Marksman skill level required
set SBAMFocusShotSkillLevelGlobal to			0 ; Journeyman (0), Expert (1), Master (2)

;========================================================================;
; Dev-only settings ;
;========================================================================;
; Display Debug Text
set SBAMDebugGlobal to 		    				0 ;0 Off, 1 On