{
  patch_cobl_ooo_version_check.pas

  Modifies cobPatchOOOQS SCTX in the loaded "Cobl Tweaks - OOO.esp" so the
  legacy version check (incompatible with OOO Updated 1.7) is bypassed.
  After running, oblivion-batch-compile must be run on the same .esp to
  regenerate SCDA bytecode.

  IMPORTANT: do not place curly braces of any kind inside this block
  comment - JvInterpreter ends the comment at the first close-brace and
  the leftover text reaches the parser as code.
}
unit UserScript;

const
  TARGET_ESP = 'Cobl Tweaks - OOO.esp';
  TARGET_EDID = 'cobPatchOOOQS';
  NEW_SCTX = 'scn cobPatchOOOQS' + #13#10 +
             '' + #13#10 +
             ';--Reborn override 2026-04-30: skip legacy version check.' + #13#10 +
             ';  Original Cobl check expected OOOVersionControl.Version >= 34 (legacy).' + #13#10 +
             ';  OOO Updated 1.7 sets Version=150 but does not flip OOOVersionInfoAvailable,' + #13#10 +
             ';  so Cobl always reads 0 and shows the "prior to v1.34" popup. We just' + #13#10 +
             ';  short-circuit the check, set the flag, and advance to stage 2 directly.' + #13#10 +
             '' + #13#10 +
             'long  HasTweak' + #13#10 +
             'long  OOOVersionInfoAvailable' + #13#10 +
             'long  ReqOOO' + #13#10 +
             'long  ReqOOOBeta' + #13#10 +
             'long  ReqOOOAlpha' + #13#10 +
             'float fQuestDelayTime' + #13#10 +
             'long  sleepMode' + #13#10 +
             'long  count' + #13#10 +
             'long  state' + #13#10 +
             'long  converted' + #13#10 +
             '' + #13#10 +
             'begin gameMode' + #13#10 +
             #9 + 'if HasTweak' + #13#10 +
             #9#9 + 'return' + #13#10 +
             #9 + 'endif' + #13#10 +
             #9 + 'set ReqOOO to 34' + #13#10 +
             #9 + 'set OOOVersionInfoAvailable to 1' + #13#10 +
             #9 + 'SetStage cobPatchOOOQ 2' + #13#10 +
             #9 + 'set HasTweak to 1' + #13#10 +
             'end' + #13#10;

function FindFileByName(const name: string): IInterface;
var
  i: Integer;
  f: IInterface;
begin
  Result := nil;
  for i := 0 to Pred(FileCount) do begin
    f := FileByIndex(i);
    if GetFileName(f) = name then begin
      Result := f;
      Exit;
    end;
  end;
end;

function Initialize: Integer;
var
  targetFile: IInterface;
  i: Integer;
  rec, override: IInterface;
  sctxElem: IInterface;
  scdaElem: IInterface;
  found: Boolean;
begin
  targetFile := FindFileByName(TARGET_ESP);
  if not Assigned(targetFile) then begin
    AddMessage('ERROR: ' + TARGET_ESP + ' not loaded');
    Result := 1;
    Exit;
  end;
  AddMessage('Found ' + TARGET_ESP + ', searching for ' + TARGET_EDID + '...');

  found := False;
  for i := 0 to Pred(RecordCount(targetFile)) do begin
    rec := RecordByIndex(targetFile, i);
    if (Signature(rec) = 'SCPT') and (EditorID(rec) = TARGET_EDID) then begin
      AddMessage('Found ' + TARGET_EDID + ' at index ' + IntToStr(i));

      // Set SCTX
      sctxElem := ElementBySignature(rec, 'SCTX');
      if not Assigned(sctxElem) then begin
        sctxElem := Add(rec, 'SCTX', True);
      end;
      SetEditValue(sctxElem, NEW_SCTX);
      AddMessage('Updated SCTX (' + IntToStr(Length(NEW_SCTX)) + ' chars)');

      // Empty SCDA so oblivion-batch-compile knows to recompile
      scdaElem := ElementBySignature(rec, 'SCDA');
      if Assigned(scdaElem) then begin
        SetEditValue(scdaElem, '');
        AddMessage('Cleared SCDA (will be regenerated by oblivion-batch-compile)');
      end;

      found := True;
      Break;
    end;
  end;

  if not found then begin
    AddMessage('ERROR: ' + TARGET_EDID + ' not found in ' + TARGET_ESP);
    Result := 1;
    Exit;
  end;

  // Save the modified ESP programmatically
  try
    SaveFile(targetFile);
    AddMessage('Saved ' + TARGET_ESP + ' to its source mod folder.');
  except
    AddMessage('NOTE: SaveFile() failed; save manually via xEdit File > Save.');
  end;

  AddMessage('Done. Next: run oblivion-batch-compile on this ESP to regenerate SCDA.');
  Result := 0;
end;

end.
