"""Compute precision/recall on G5's vanilla-50 corpus.

For each NPC in g5/validation_vanilla.jsonl, look up the predictor's output
and compute:
  - True positive: predictor says naked, actually naked.
  - False positive: predictor says naked, actually has gear.
  - False negative: predictor says ok, actually naked.
  - True negative: predictor says ok, actually has gear.

Skips NPCs flagged has_script in the predictor output (S1 boundary).
Writes a Markdown summary to predictor/calibration_report.md.
"""
import argparse
import json
from pathlib import Path


def load_predictions(path: Path) -> dict[str, dict]:
    out: dict[str, dict] = {}
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            r = json.loads(line)
            out[r["fid"].upper()] = r
    return out


def load_g5(path: Path) -> list[dict]:
    rows: list[dict] = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rows.append(json.loads(line))
    return rows


def is_actually_naked(g5_row: dict) -> bool:
    """Proxy: NPC has zero items in runtime inventory.

    The G5 inventory output doesn't carry signatures, only form_ids. For the
    spike, "0 items" is the cleanest signal of "this NPC is broken." A more
    nuanced check would walk to ARMO/CLOT specifically — left as a follow-up.
    """
    inv = g5_row.get("inventory", [])
    return len(inv) == 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--predictions", required=True, type=Path)
    ap.add_argument("--g5", required=True, type=Path)
    ap.add_argument("--report", required=True, type=Path)
    args = ap.parse_args()

    preds = load_predictions(args.predictions)
    g5 = load_g5(args.g5)

    tp = fp = fn = tn = 0
    skipped_script = 0
    skipped_not_in_predictions = 0
    review_rows: list[dict] = []

    for row in g5:
        fid = row["form_id"].upper()
        if fid not in preds:
            skipped_not_in_predictions += 1
            continue
        pred = preds[fid]
        if pred["has_script"]:
            skipped_script += 1
            continue
        actually_naked = is_actually_naked(row)
        predicted_naked = pred["predicted_naked"]
        if predicted_naked and actually_naked:
            tp += 1
        elif predicted_naked and not actually_naked:
            fp += 1
            # Apparent FP — but could be a Dremora-class TP (visually broken
            # despite non-empty inventory). Capture for operator spot-review.
            review_rows.append({
                "form_id": fid,
                "edid": row.get("edid"),
                "predicted_reason": pred.get("reason"),
                "predicted_missing_meshes": pred.get("missing_meshes", []),
                "g5_inventory_count": len(row.get("inventory", [])),
            })
        elif (not predicted_naked) and actually_naked:
            fn += 1
        else:
            tn += 1

    total_scored = tp + fp + fn + tn
    precision = tp / (tp + fp) if (tp + fp) else 0.0
    recall = tp / (tp + fn) if (tp + fn) else 0.0
    accuracy = (tp + tn) / total_scored if total_scored else 0.0

    # Note: the G5 corpus is all known-good (clothed) NPCs — zero actually-naked
    # entries — so TP=0, FN=0, and precision/recall collapse to degenerate values.
    # What IS meaningful here is the false-positive rate (FP / total_scored) which
    # directly measures how aggressively the predictor over-fires on vanilla NPCs.
    fpr = fp / total_scored if total_scored else 0.0
    true_negative_rate = tn / total_scored if total_scored else 0.0

    lines = [
        "# Predictor calibration report",
        "",
        f"**Date:** generated by `compute_metrics.py`",
        f"**G5 corpus:** {args.g5}",
        f"**Predictions:** {args.predictions}",
        "",
        "## Counts",
        f"- True positives (predicted naked, actually naked):   {tp}",
        f"- False positives (predicted naked, actually clothed): {fp}",
        f"- False negatives (predicted ok, actually naked):     {fn}",
        f"- True negatives (predicted ok, actually clothed):    {tn}",
        f"- Skipped (has_script in prediction):                  {skipped_script}",
        f"- Skipped (G5 NPC not in predictions):                 {skipped_not_in_predictions}",
        f"- Total scored (no-script bucket):                     {total_scored}",
        "",
        "## Metrics (no-script bucket)",
        f"- **Precision:** {precision:.3f}  (target ≥ 0.90)",
        f"- **Recall:**    {recall:.3f}  (target ≥ 0.80)",
        f"- Accuracy:    {accuracy:.3f}",
        "",
        "## False-positive analysis",
        f"- **False-positive rate (FP / total_scored):** {fpr:.3f}",
        f"  ({fp} of {total_scored} clothed NPCs incorrectly flagged as naked)",
        f"- **True-negative rate (specificity):** {true_negative_rate:.3f}",
        f"  ({tn} of {total_scored} clothed NPCs correctly passed)",
        "",
        "## Spec gates",
        f"- Precision ≥ 0.90: {'PASS' if precision >= 0.90 else 'FAIL'}",
        f"- Recall    ≥ 0.80: {'PASS' if recall >= 0.80 else 'FAIL'}",
        "",
        "## Corpus note",
        "The G5 vanilla-50 corpus contains **only known-good (clothed) NPCs** —",
        "it was built by spawning 50 vanilla NPCs that T15 confirmed all returned",
        "non-empty inventories. This means:",
        "",
        "- TP = 0 and FN = 0 by construction (no actually-naked NPCs in corpus).",
        "- Precision and Recall are degenerate metrics here (0/0 → 0.0).",
        "- The **meaningful calibration signal is the false-positive rate**:",
        f"  {fp}/{total_scored} clothed NPCs ({fpr*100:.1f}%) were incorrectly predicted naked.",
        "",
        "To compute true precision/recall, the corpus needs naked-NPC ground-truth",
        "entries (e.g. from the Dremora finding in the T15 report, or from the",
        "OOO Enhanced 248 net-negative NPCs sampled empirically).",
        "",
        "## Verdict",
        f"{'Spike succeeds' if precision >= 0.90 and recall >= 0.80 else 'Below target — examine false positives/negatives'}",
        "",
        "**Honest assessment:** Precision/recall gates are formally FAIL because the",
        "G5 corpus has no positive (naked) examples, making both metrics degenerate.",
        "The real finding is a **{:.0f}% false-positive rate on vanilla clothed NPCs**.".format(fpr * 100),
        "Root cause: BSA index is incomplete (SI DLC BSAs not indexed), so vanilla",
        "armor mesh paths that ship in SI BSAs appear missing, inflating predicted_naked.",
        "Calibration against a corpus with both positive and negative examples is needed",
        "to compute valid precision/recall.",
    ]
    args.report.write_text("\n".join(lines), encoding="utf-8")

    review_path = args.report.with_suffix(".review.json")
    review_path.write_text(json.dumps(review_rows, indent=2), encoding="utf-8")

    import sys
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    print("\n".join(lines))
    print(f"\n{len(review_rows)} apparent FPs written to {review_path} for spot-check")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
